<?php

/* File to define constants used in the codebase. */

/* Name of template files */
define('TEMPLATE_ATTENDANCE', 'attendance.html');
define('TEMPLATE_SINGLE_COURSE', 'single-course.html');

/* Application-specific error messages */
define('ERROR_STUDENT_NOT_FOUND', 'A student was not found based on the provided information.');
define('ERROR_INVALID_INPUT', 'The provided input could not be used to query Populi for a student id.');
define('ERROR_INVALID_DATA', 'The attendance data was in an incorrect format to render.');
