<?php

/* File to define constants used in the codebase. */

/* Name of template file */
define('TEMPLATE_FILE', 'attendance.html');

/* Error messages */
define('ERROR_STUDENT_NOT_FOUND', 'A student was not found based on the provided information.');
define('ERROR_INVALID_INPUT', 'The provided input could not be used to query Populi for a student id.');
define('ERROR_INVALID_DATA', 'The attendance data was in an incorrect format to render.');
define('ERROR_EXCEPTION', 'A fatal error has occurred.');